FROM fedora:44

RUN dnf install -y \
    appstream \
    cmake \
    extra-cmake-modules \
    gcc-c++ \
    git \
    just \
    kf6-kcoreaddons-devel \
    kf6-ki18n-devel \
    kf6-knotifications-devel \
    kf6-kwallet-devel \
    libplasma-devel \
    libsecret-devel \
    ninja-build \
    openssl-devel \
    python3 \
    python3-PyQt6 \
    qt6-qtbase \
    qt6-qtbase-devel \
    qt6-qtdeclarative-devel \
    rpmlint \
    && dnf clean all
